/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author GabrielWeilBriskiews
 */
public class AppGraphicsPagamento extends javax.swing.JFrame {

    /**
     * Creates new form AppGraphicsPagamento
     */
    public AppGraphicsPagamento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_data_pagamento = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_forma_pagamento = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_valor = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Cadastro de pagamento");

        jLabel2.setText("Data de pagamento: ");

        jLabel3.setText("Forma de pagamento:");

        jLabel4.setText("Valor: ");

        jButton7.setText("Atualizar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Excluir");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Pesquisar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel5.setText("ID:");

        jLabel6.setText("Nome: ");

        txt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(304, 304, 304)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton7)
                                .addGap(14, 14, 14)
                                .addComponent(jButton8)
                                .addGap(18, 18, 18)
                                .addComponent(jButton9))
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_valor, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_forma_pagamento, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_data_pagamento, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txt_nome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)))))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_data_pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_forma_pagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton7)
                    .addComponent(jButton9)
                    .addComponent(jButton8)
                    .addComponent(jButton2))
                .addGap(0, 232, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            String driverName = "com.mysql.jdbc.Driver";
            try {
                Class.forName(driverName);
            } catch (ClassNotFoundException ex) {
                //Logger.getLogger(Pesquisar.class.getName()).log(Level.SEVERE, null, ex);
            }

            // Configurando a nossa conexão com um banco de dados//
            String serverName = "viajuntos.sytes.net";    //caminho do servidor do BD

            String mydatabase = "progb2023";        //nome do seu banco de dados

            String url = "jdbc:mysql://" + serverName + "/" + mydatabase + "?useUnicode=true&characterEncoding=UTF8";

            String username = "admin_progb2023";        //nome de um usuário de seu BD      

            String password = "admin_progb2023";      //sua senha de acesso

            Connection conn = (Connection) DriverManager.getConnection(url, username, password);

            Statement stmt = (Statement) conn.createStatement();      
            
            String id = txt_id.getText();
            String nome = txt_nome.getText();
            String data_pagamento = txt_data_pagamento.getText();
            String forma_pagamento = txt_forma_pagamento.getText();
            String valor = txt_valor.getText();
            
            
            stmt.execute("INSERT INTO gabriel_pagamento(nome,data_pagamento,forma_pagamento,valor) VALUES('"+nome+"','"+data_pagamento+"', '"+forma_pagamento+"', '"+valor+"');");  ///preparaco da insercao do registro
            
            conn.close();
            
            System.out.println("Salvo com sucesso ");

        }         
          
           catch (SQLException e) {
               System.out.println(e.getLocalizedMessage());
           } 
        
        try {
         
       }
       catch (NumberFormatException ErrodeFormato){
        
        System.out.println("erro de formatação ");
        System.out.println("falha geral = "+ErrodeFormato.getMessage());
        System.out.println("causa = "+ErrodeFormato.getCause());
        System.out.println("localizando mensagem = "+ErrodeFormato.getLocalizedMessage());
        System.out.println("stack trace = "+ErrodeFormato.getStackTrace());

        }
        
        
        catch (ArithmeticException ErroMatematico){
        
        System.out.println("erro matematico ");
        System.out.println("falha geral = "+ErroMatematico.getMessage());
        System.out.println("causa = "+ErroMatematico.getCause());
        System.out.println("localizando mensagem = "+ErroMatematico.getLocalizedMessage());
        System.out.println("stack trace = "+ErroMatematico.getStackTrace());

        }
        
        catch (Exception ErroGenerico){
        
        System.out.println("erro matematico ");
        System.out.println("falha geral = "+ErroGenerico.getMessage());
        System.out.println("causa = "+ErroGenerico.getCause());
        System.out.println("localizando mensagem = "+ErroGenerico.getLocalizedMessage());
        System.out.println("stack trace = "+ErroGenerico.getStackTrace());
        
    
                                       
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            
        txt_nome.setText("");
        txt_forma_pagamento.setText("");
        txt_data_pagamento.setText("");
        txt_valor.setText("");
        
    
       }
       catch (NumberFormatException ErrodeFormato){
        
        System.out.println("erro de formatação ");
        System.out.println("falha geral = "+ErrodeFormato.getMessage());
        System.out.println("causa = "+ErrodeFormato.getCause());
        System.out.println("localizando mensagem = "+ErrodeFormato.getLocalizedMessage());
        System.out.println("stack trace = "+ErrodeFormato.getStackTrace());

        }
        
        
        catch (ArithmeticException ErroMatematico){
        
        System.out.println("erro matematico ");
        System.out.println("falha geral = "+ErroMatematico.getMessage());
        System.out.println("causa = "+ErroMatematico.getCause());
        System.out.println("localizando mensagem = "+ErroMatematico.getLocalizedMessage());
        System.out.println("stack trace = "+ErroMatematico.getStackTrace());

        }
        
        catch (Exception ErroGenerico){
        
        System.out.println("erro matematico ");
        System.out.println("falha geral = "+ErroGenerico.getMessage());
        System.out.println("causa = "+ErroGenerico.getCause());
        System.out.println("localizando mensagem = "+ErroGenerico.getLocalizedMessage());
        System.out.println("stack trace = "+ErroGenerico.getStackTrace());
        
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {

            String driverName = "com.mysql.jdbc.Driver";

            Class.forName(driverName);

            // Configurando a nossa conexão com um banco de dados//
            String serverName = "viajuntos.sytes.net";    //caminho do servidor do BD

            String mydatabase = "progb2023";        //nome do seu banco de dados

            String url = "jdbc:mysql://" + serverName + "/" + mydatabase + "?useUnicode=true&characterEncoding=UTF8";

            String username = "admin_progb2023";        //nome de um usuário de seu BD      

            String password = "admin_progb2023";      //sua senha de acesso

            Connection conn = (Connection) DriverManager.getConnection(url, username, password);

            Statement stmt = (Statement) conn.createStatement();

            //ResultSet rs = stmt.executeQuery( "SELECT nome FROM cliente WHERE color = 'blue'" );
            String nome = txt_nome.getText();
            String data_pagamento = txt_data_pagamento.getText();
            String forma_pagamento = txt_forma_pagamento.getText();
            String valor = txt_valor.getText();
            String id = txt_id.getText();

            stmt.execute("UPDATE gabriel_pagamento SET nome = '"+nome+"', data_pagamento = '"+data_pagamento+"', forma_pagamento = '"+forma_pagamento+"', "
                    + "valor = '"+valor+"'  WHERE id = "+id);
            System.out.println("atualizado com sucesso");
            conn.close();

        }         
          
           catch (SQLException e) {
               System.out.println(e.getLocalizedMessage());
           } catch (ClassNotFoundException ex) {
            Logger.getLogger(AppGraphicGerente.class.getName()).log(Level.SEVERE, null, ex);
        }
 
        try {
           
       }
       catch (NumberFormatException ErrodeFormato){
        
        System.out.println("erro de formatação ");
        System.out.println("falha geral = "+ErrodeFormato.getMessage());
        System.out.println("causa = "+ErrodeFormato.getCause());
        System.out.println("localizando mensagem = "+ErrodeFormato.getLocalizedMessage());
        System.out.println("stack trace = "+ErrodeFormato.getStackTrace());

        }
        
        
        catch (ArithmeticException ErroMatematico){
        
        System.out.println("erro matematico ");
        System.out.println("falha geral = "+ErroMatematico.getMessage());
        System.out.println("causa = "+ErroMatematico.getCause());
        System.out.println("localizando mensagem = "+ErroMatematico.getLocalizedMessage());
        System.out.println("stack trace = "+ErroMatematico.getStackTrace());

        }
        
        catch (Exception ErroGenerico){
        
        System.out.println("erro matematico ");
        System.out.println("falha geral = "+ErroGenerico.getMessage());
        System.out.println("causa = "+ErroGenerico.getCause());
        System.out.println("localizando mensagem = "+ErroGenerico.getLocalizedMessage());
        System.out.println("stack trace = "+ErroGenerico.getStackTrace());
        
    }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {

            String driverName = "com.mysql.jdbc.Driver";

            Class.forName(driverName);

            // Configurando a nossa conexão com um banco de dados//
            String serverName = "viajuntos.sytes.net";    //caminho do servidor do BD

            String mydatabase = "progb2023";        //nome do seu banco de dados

            String url = "jdbc:mysql://" + serverName + "/" + mydatabase + "?useUnicode=true&characterEncoding=UTF8";

            String username = "admin_progb2023";        //nome de um usuário de seu BD      

            String password = "admin_progb2023";      //sua senha de acesso

            Connection conn = (Connection) DriverManager.getConnection(url, username, password);

            Statement stmt = (Statement) conn.createStatement();

            
            String id  = txt_id.getText();;
            stmt.execute("DELETE FROM gabriel_pagamento WHERE id = '"+id+"' ");
            System.out.println("Deletado com sucesso");
            conn.close();

        }         
          
           catch (SQLException e) {
               System.out.println(e.getLocalizedMessage());
           } catch (ClassNotFoundException ex) {
            Logger.getLogger(AppGraphicsPagamento.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
           
       }
       catch (NumberFormatException ErrodeFormato){
        
        System.out.println("erro de formatação ");
        System.out.println("falha geral = "+ErrodeFormato.getMessage());
        System.out.println("causa = "+ErrodeFormato.getCause());
        System.out.println("localizando mensagem = "+ErrodeFormato.getLocalizedMessage());
        System.out.println("stack trace = "+ErrodeFormato.getStackTrace());

        }
        
        
        catch (ArithmeticException ErroMatematico){
        
        System.out.println("erro matematico ");
        System.out.println("falha geral = "+ErroMatematico.getMessage());
        System.out.println("causa = "+ErroMatematico.getCause());
        System.out.println("localizando mensagem = "+ErroMatematico.getLocalizedMessage());
        System.out.println("stack trace = "+ErroMatematico.getStackTrace());

        }
        
        catch (Exception ErroGenerico){
        
        System.out.println("erro matematico ");
        System.out.println("falha geral = "+ErroGenerico.getMessage());
        System.out.println("causa = "+ErroGenerico.getCause());
        System.out.println("localizando mensagem = "+ErroGenerico.getLocalizedMessage());
        System.out.println("stack trace = "+ErroGenerico.getStackTrace());
        
    }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {
            try {
            String driverName = "com.mysql.jdbc.Driver";
            try {
                Class.forName(driverName);
            } catch (ClassNotFoundException ex) {
                //Logger.getLogger(Pesquisar.class.getName()).log(Level.SEVERE, null, ex);
            }

            // Configurando a nossa conexão com um banco de dados//
            String serverName = "viajuntos.sytes.net";    //caminho do servidor do BD

            String mydatabase = "progb2023";        //nome do seu banco de dados

            String url = "jdbc:mysql://" + serverName + "/" + mydatabase + "?useUnicode=true&characterEncoding=UTF8";

            String username = "admin_progb2023";        //nome de um usuário de seu BD      

            String password = "admin_progb2023";      //sua senha de acesso

            Connection conn = (Connection) DriverManager.getConnection(url, username, password);

            Statement stmt = (Statement) conn.createStatement();

            String id_a = txt_id.getText();

            ResultSet rs = stmt.executeQuery( "SELECT * FROM gabriel_pagamento WHERE id = "+id_a  );
            
            
          while (rs.next()) {               
                String id = rs.getString("id");
                String nome = rs.getString("nome");
                String forma_pagamento = rs.getString("forma_pagamento");
                String data_pagamento = rs.getString("data_pagamento");
                String valor = rs.getString("valor");

                System.out.println("ID= "+id+" nome= "+nome);
                txt_nome.setText(nome);
                System.out.println("ID= "+id+" forma_pagamento= "+forma_pagamento);
                txt_forma_pagamento.setText(forma_pagamento);
                System.out.println("ID= "+id+" data_pagamento= "+data_pagamento);
                txt_data_pagamento.setText(data_pagamento);
                System.out.println("ID= "+id+" valor= "+valor);
                txt_valor.setText(valor);
                
            }
            
            
            
            conn.close();

        }         
          
           catch (SQLException e) {
               System.out.println(e.getLocalizedMessage());
           }
           
       }
       catch (NumberFormatException ErrodeFormato){
        
        System.out.println("erro de formatação ");
        System.out.println("falha geral = "+ErrodeFormato.getMessage());
        System.out.println("causa = "+ErrodeFormato.getCause());
        System.out.println("localizando mensagem = "+ErrodeFormato.getLocalizedMessage());
        System.out.println("stack trace = "+ErrodeFormato.getStackTrace());

        }
        
        
        catch (ArithmeticException ErroMatematico){
        
        System.out.println("erro matematico ");
        System.out.println("falha geral = "+ErroMatematico.getMessage());
        System.out.println("causa = "+ErroMatematico.getCause());
        System.out.println("localizando mensagem = "+ErroMatematico.getLocalizedMessage());
        System.out.println("stack trace = "+ErroMatematico.getStackTrace());

        }
        
        catch (Exception ErroGenerico){
        
        System.out.println("erro matematico ");
        System.out.println("falha geral = "+ErroGenerico.getMessage());
        System.out.println("causa = "+ErroGenerico.getCause());
        System.out.println("localizando mensagem = "+ErroGenerico.getLocalizedMessage());
        System.out.println("stack trace = "+ErroGenerico.getStackTrace());
        
    }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void txt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppGraphicsPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppGraphicsPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppGraphicsPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppGraphicsPagamento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppGraphicsPagamento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JFormattedTextField txt_data_pagamento;
    private javax.swing.JFormattedTextField txt_forma_pagamento;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JTextField txt_valor;
    // End of variables declaration//GEN-END:variables
}
