/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projeto;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.io.FileWriter;
import java.io.PrintWriter;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author GabrielWeilBriskiews
 */
public class AppGraphicsCliente extends javax.swing.JFrame {

    /**
     * Creates new form AppGraphicsCliente
     */
    public AppGraphicsCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_telefone = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Pesquisar = new javax.swing.JButton();
        txt_senha = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        txt_email = new javax.swing.JTextField();
        txt_mostrasenha = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        txt_data_nascimento = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_id = new javax.swing.JTextField();
        txt_cpf = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_telefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_telefoneActionPerformed(evt);
            }
        });

        jButton8.setText("Excluir");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        Pesquisar.setText("Pesquisar");
        Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PesquisarActionPerformed(evt);
            }
        });

        txt_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_senhaActionPerformed(evt);
            }
        });

        jLabel7.setText("E-mail:");

        jButton3.setText("Mostrar Senha");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txt_mostrasenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_mostrasenhaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Cadastro do cliente");

        txt_data_nascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_data_nascimentoActionPerformed(evt);
            }
        });

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("ID:");

        jLabel5.setText("CPF:");

        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Senha:");

        jLabel4.setText("Data de Nascimento:");

        jLabel6.setText("Telefone:");

        jButton7.setText("Atualizar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(294, 294, 294))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_mostrasenha, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton3)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton1)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton7)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton8)
                                        .addGap(18, 18, 18)
                                        .addComponent(Pesquisar))))
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_data_nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(110, 110, 110))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(336, 336, 336)))
                        .addGap(22, 218, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_data_nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addComponent(txt_mostrasenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton7)
                            .addComponent(jButton8)
                            .addComponent(Pesquisar)))
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_telefoneActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {

            String driverName = "com.mysql.jdbc.Driver";

            Class.forName(driverName);

            // Configurando a nossa conexão com um banco de dados//
            String serverName = "viajuntos.sytes.net";    //caminho do servidor do BD

            String mydatabase = "progb2023";        //nome do seu banco de dados

            String url = "jdbc:mysql://" + serverName + "/" + mydatabase + "?useUnicode=true&characterEncoding=UTF8";

            String username = "admin_progb2023";        //nome de um usuário de seu BD

            String password = "admin_progb2023";      //sua senha de acesso

            Connection conn = (Connection) DriverManager.getConnection(url, username, password);

            Statement stmt = (Statement) conn.createStatement();

            //ResultSet rs = stmt.executeQuery( "SELECT nome FROM cliente WHERE color = 'blue'" );
            String id  = txt_id.getText();;
            stmt.execute("DELETE FROM gabriel_pessoa WHERE id = '"+id+"' ");
            System.out.println("Deletado com sucesso");
            conn.close();

        }

        catch (SQLException e) {
            System.out.println(e.getLocalizedMessage());
        }

        catch (NumberFormatException ErrodeFormato){

            System.out.println("erro de formatação ");
            System.out.println("falha geral = "+ErrodeFormato.getMessage());
            System.out.println("causa = "+ErrodeFormato.getCause());
            System.out.println("localizando mensagem = "+ErrodeFormato.getLocalizedMessage());
            System.out.println("stack trace = "+ErrodeFormato.getStackTrace());

        }

        catch (ArithmeticException ErroMatematico){

            System.out.println("erro matematico ");
            System.out.println("falha geral = "+ErroMatematico.getMessage());
            System.out.println("causa = "+ErroMatematico.getCause());
            System.out.println("localizando mensagem = "+ErroMatematico.getLocalizedMessage());
            System.out.println("stack trace = "+ErroMatematico.getStackTrace());

        }

        catch (Exception ErroGenerico){

            System.out.println("erro matematico ");
            System.out.println("falha geral = "+ErroGenerico.getMessage());
            System.out.println("causa = "+ErroGenerico.getCause());
            System.out.println("localizando mensagem = "+ErroGenerico.getLocalizedMessage());
            System.out.println("stack trace = "+ErroGenerico.getStackTrace());

        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PesquisarActionPerformed
        try {

            String driverName = "com.mysql.jdbc.Driver";
            try {
                Class.forName(driverName);
            } catch (ClassNotFoundException ex) {
                //Logger.getLogger(Pesquisar.class.getName()).log(Level.SEVERE, null, ex);
            }

            // Configurando a nossa conexão com um banco de dados//
            String serverName = "viajuntos.sytes.net";    //caminho do servidor do BD

            String mydatabase = "progb2023";        //nome do seu banco de dados

            String url = "jdbc:mysql://" + serverName + "/" + mydatabase + "?useUnicode=true&characterEncoding=UTF8";

            String username = "admin_progb2023";        //nome de um usuário de seu BD

            String password = "admin_progb2023";      //sua senha de acesso

            Connection conn = (Connection) DriverManager.getConnection(url, username, password);

            Statement stmt = (Statement) conn.createStatement();
            String id_a = txt_id.getText();

            ResultSet rs = stmt.executeQuery( "SELECT * FROM gabriel_pessoa WHERE id = "+id_a );

            while (rs.next()) {
                String id = rs.getString("id");
                String nome = rs.getString("nome");
                String cpf = rs.getString("cpf");
                String email = rs.getString("email");
                String data_nascimento = rs.getString("data_nascimento");
                String telefone = rs.getString("telefone");
                
                System.out.println("ID= "+id+" nome= "+nome);
                txt_nome.setText(nome);
                System.out.println("ID= "+id+" cpf= "+cpf);
                txt_cpf.setText(cpf);
                System.out.println("ID= "+id+" email= "+email);
                txt_email.setText(email);
                System.out.println("ID= "+id+" data_nascimento= "+data_nascimento);
                txt_data_nascimento.setText(data_nascimento);
                System.out.println("ID= "+id+" telefone= "+telefone);
                txt_telefone.setText(telefone);
            }

            conn.close();

        }

        catch (SQLException e) {
            System.out.println(e.getLocalizedMessage());
        }

        try {

        }
        catch (NumberFormatException ErrodeFormato){

            System.out.println("erro de formatação ");
            System.out.println("falha geral = "+ErrodeFormato.getMessage());
            System.out.println("causa = "+ErrodeFormato.getCause());
            System.out.println("localizando mensagem = "+ErrodeFormato.getLocalizedMessage());
            System.out.println("stack trace = "+ErrodeFormato.getStackTrace());

        }

        catch (ArithmeticException ErroMatematico){

            System.out.println("erro matematico ");
            System.out.println("falha geral = "+ErroMatematico.getMessage());
            System.out.println("causa = "+ErroMatematico.getCause());
            System.out.println("localizando mensagem = "+ErroMatematico.getLocalizedMessage());
            System.out.println("stack trace = "+ErroMatematico.getStackTrace());

        }

        catch (Exception ErroGenerico){

            System.out.println("erro matematico ");
            System.out.println("falha geral = "+ErroGenerico.getMessage());
            System.out.println("causa = "+ErroGenerico.getCause());
            System.out.println("localizando mensagem = "+ErroGenerico.getLocalizedMessage());
            System.out.println("stack trace = "+ErroGenerico.getStackTrace());

        }
    }//GEN-LAST:event_PesquisarActionPerformed

    private void txt_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_senhaActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_txt_senhaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String senha = txt_senha.getText();
        txt_mostrasenha.setText(senha);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txt_mostrasenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_mostrasenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_mostrasenhaActionPerformed

    private void txt_data_nascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_data_nascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_data_nascimentoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            String driverName = "com.mysql.jdbc.Driver";
            try {
                Class.forName(driverName);
            } catch (ClassNotFoundException ex) {
                //Logger.getLogger(Pesquisar.class.getName()).log(Level.SEVERE, null, ex);
            }

            // Configurando a nossa conexão com um banco de dados//
            String serverName = "viajuntos.sytes.net";    //caminho do servidor do BD

            String mydatabase = "progb2023";        //nome do seu banco de dados

            String url = "jdbc:mysql://" + serverName + "/" + mydatabase + "?useUnicode=true&characterEncoding=UTF8";

            String username = "admin_progb2023";        //nome de um usuário de seu BD

            String password = "admin_progb2023";      //sua senha de acesso

            Connection conn = (Connection) DriverManager.getConnection(url, username, password);

            Statement stmt = (Statement) conn.createStatement();

            String email = txt_email.getText();
            String nome = txt_nome.getText();
            String cpf = txt_cpf.getText();
            String telefone = txt_telefone.getText();
            String data_nascimento = txt_data_nascimento.getText();

            stmt.execute("INSERT INTO gabriel_pessoa(nome,email,cpf,telefone,data_nascimento) VALUES('"+nome+"','"+email+"',"
                + "'"+cpf+"','"+telefone+"','"+data_nascimento+"');");  ///preparaco da insercao do registro

            conn.close();

            System.out.println("Salvo com sucesso ");

        }

        catch (SQLException e) {
            System.out.println(e.getLocalizedMessage());
        }

        try {

           // FileWriter arq = new FileWriter("c:\\Arquivos_java\\projeto.txt");
            //PrintWriter gravarArq = new PrintWriter(arq);
            String nome = txt_nome.getText();
            String data_nasc = txt_data_nascimento.getText();
            String cpf = txt_cpf.getText();
            String telefone = txt_telefone.getText();
            String email = txt_email.getText();

            //gravarArq.printf("Nome: \n"+nome+ "Data_nascimento: \n"+data_nasc+
              //  "Cpf: \n"+cpf+ "Telefone: \n"+telefone+ "E-mail: \n"+email);
            //gravarArq.close();

        }
        catch (NumberFormatException ErrodeFormato){

            System.out.println("erro de formatação ");
            System.out.println("falha geral = "+ErrodeFormato.getMessage());
            System.out.println("causa = "+ErrodeFormato.getCause());
            System.out.println("localizando mensagem = "+ErrodeFormato.getLocalizedMessage());
            System.out.println("stack trace = "+ErrodeFormato.getStackTrace());

        }

        catch (ArithmeticException ErroMatematico){

            System.out.println("erro matematico ");
            System.out.println("falha geral = "+ErroMatematico.getMessage());
            System.out.println("causa = "+ErroMatematico.getCause());
            System.out.println("localizando mensagem = "+ErroMatematico.getLocalizedMessage());
            System.out.println("stack trace = "+ErroMatematico.getStackTrace());

        }

        catch (Exception ErroGenerico){

            System.out.println("erro matematico ");
            System.out.println("falha geral = "+ErroGenerico.getMessage());
            System.out.println("causa = "+ErroGenerico.getCause());
            System.out.println("localizando mensagem = "+ErroGenerico.getLocalizedMessage());
            System.out.println("stack trace = "+ErroGenerico.getStackTrace());

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {

            txt_nome.setText("");
            txt_senha.setText("");
            txt_mostrasenha.setText("");
            txt_email.setText("");
            txt_cpf.setText("");
            txt_telefone.setText("");
            txt_data_nascimento.setText("");

        }
        catch (NumberFormatException ErrodeFormato){

            System.out.println("erro de formatação ");
            System.out.println("falha geral = "+ErrodeFormato.getMessage());
            System.out.println("causa = "+ErrodeFormato.getCause());
            System.out.println("localizando mensagem = "+ErrodeFormato.getLocalizedMessage());
            System.out.println("stack trace = "+ErrodeFormato.getStackTrace());

        }

        catch (ArithmeticException ErroMatematico){

            System.out.println("erro matematico ");
            System.out.println("falha geral = "+ErroMatematico.getMessage());
            System.out.println("causa = "+ErroMatematico.getCause());
            System.out.println("localizando mensagem = "+ErroMatematico.getLocalizedMessage());
            System.out.println("stack trace = "+ErroMatematico.getStackTrace());

        }

        catch (Exception ErroGenerico){

            System.out.println("erro matematico ");
            System.out.println("falha geral = "+ErroGenerico.getMessage());
            System.out.println("causa = "+ErroGenerico.getCause());
            System.out.println("localizando mensagem = "+ErroGenerico.getLocalizedMessage());
            System.out.println("stack trace = "+ErroGenerico.getStackTrace());

        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {

            String driverName = "com.mysql.jdbc.Driver";

            Class.forName(driverName);

            // Configurando a nossa conexão com um banco de dados//
            String serverName = "viajuntos.sytes.net";    //caminho do servidor do BD

            String mydatabase = "progb2023";        //nome do seu banco de dados

            String url = "jdbc:mysql://" + serverName + "/" + mydatabase + "?useUnicode=true&characterEncoding=UTF8";

            String username = "admin_progb2023";        //nome de um usuário de seu BD

            String password = "admin_progb2023";      //sua senha de acesso

            Connection conn = (Connection) DriverManager.getConnection(url, username, password);

            Statement stmt = (Statement) conn.createStatement();

            //ResultSet rs = stmt.executeQuery( "SELECT nome FROM cliente WHERE color = 'blue'" );
            String email = txt_email.getText();
            String nome = txt_nome.getText();
            String cpf = txt_cpf.getText();
            String telefone = txt_telefone.getText();
            String data_nascimento = txt_data_nascimento.getText();
            String id = txt_id.getText();

            stmt.execute("UPDATE gabriel_pessoa SET nome = '"+nome+"', email = '"+email+"', cpf = '"+cpf+"', telefone = '"+telefone+"', data_nascimento = '"+data_nascimento+"'  WHERE id = "+id);
            System.out.println("atualizado com sucesso");
            conn.close();

        }

        catch (SQLException e) {
            System.out.println(e.getLocalizedMessage());
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(AppGraphicGerente.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO code application logic here

        catch (NumberFormatException ErrodeFormato){

            System.out.println("erro de formatação ");
            System.out.println("falha geral = "+ErrodeFormato.getMessage());
            System.out.println("causa = "+ErrodeFormato.getCause());
            System.out.println("localizando mensagem = "+ErrodeFormato.getLocalizedMessage());
            System.out.println("stack trace = "+ErrodeFormato.getStackTrace());

        }

        catch (ArithmeticException ErroMatematico){

            System.out.println("erro matematico ");
            System.out.println("falha geral = "+ErroMatematico.getMessage());
            System.out.println("causa = "+ErroMatematico.getCause());
            System.out.println("localizando mensagem = "+ErroMatematico.getLocalizedMessage());
            System.out.println("stack trace = "+ErroMatematico.getStackTrace());

        }

        catch (Exception ErroGenerico){

            System.out.println("erro matematico ");
            System.out.println("falha geral = "+ErroGenerico.getMessage());
            System.out.println("causa = "+ErroGenerico.getCause());
            System.out.println("localizando mensagem = "+ErroGenerico.getLocalizedMessage());
            System.out.println("stack trace = "+ErroGenerico.getStackTrace());

        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppGraphicsCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppGraphicsCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppGraphicsCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppGraphicsCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppGraphicsCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Pesquisar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txt_cpf;
    private javax.swing.JTextField txt_data_nascimento;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_mostrasenha;
    private javax.swing.JTextField txt_nome;
    private javax.swing.JPasswordField txt_senha;
    private javax.swing.JTextField txt_telefone;
    // End of variables declaration//GEN-END:variables
}
